# Generated by Django 5.0.7 on 2024-07-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_coumt',
            new_name='cars_count',
        ),
    ]
