# Generated by Django 5.0.7 on 2024-07-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_cars_coumt_carinventory_cars_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
